Patch HIDRemote.mm to fix compiling errors
Not sure if this was necessary because of the extension change from .m
to .mm, or because Nightingale build system uses an older XCode version
or older compiler.

For reference, below is the error output when trying to build
Nightingale with the original HIDRemote.mm code (ie. before patching):

/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/sbAppleRemoteService.mm:
In function ‘void -[AppleRemoteDelegate
onButtonPressed:isHold:](AppleRemoteDelegate*, objc_selector*,
EAppleRemoteButton,
BOOL)’:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/sbAppleRemoteService.mm:88:
warning: enumeration value ‘eUnknownButton’ not handled in
switch
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/sbAppleRemoteService.mm:
At global
scope:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/sbAppleRemoteService.mm:118:
warning: incomplete implementation of class
‘AppleRemoteDelegate’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/sbAppleRemoteService.mm:118:
warning: method definition for
‘-hidRemote:eventWithButton:isPressed:fromHardwareWithAttributes:’ not
found
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/sbAppleRemoteService.mm:118:
warning: class ‘AppleRemoteDelegate’ does not fully implement the
‘HIDRemoteDelegate’ protocol
       CXX
sbAppleRemoteModule.o
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/sbAppleRemoteModule.mm:39:47:
warning: backslash and newline separated by space
       CXX
HIDRemote.o
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:253:
warning: ignoring #pragma clang
diagnostic
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:254:
warning: ignoring #pragma clang
diagnostic
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:256:
warning: ignoring #pragma clang
diagnostic
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:
In function ‘HIDRemoteAluminumRemoteSupportLevel -[HIDRemote
aluminiumRemoteSystemSupportLevel](HIDRemote*,
objc_selector*)’:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:280:
error: invalid conversion from ‘int’ to
‘HIDRemoteAluminumRemoteSupportLevel’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:
In function ‘HIDRemoteButtonCode -[HIDRemote
buttonCodeForUsage:usagePage:](HIDRemote*, objc_selector*, unsigned int,
unsigned
int)’:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:996:
error: invalid conversion from ‘int’ to
‘HIDRemoteButtonCode’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1001:
error: invalid conversion from ‘int’ to
‘HIDRemoteButtonCode’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1006:
error: invalid conversion from ‘int’ to
‘HIDRemoteButtonCode’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:
In function ‘BOOL -[HIDRemote _setupService:](HIDRemote*,
objc_selector*,
io_object_t)’:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1122:
error: invalid conversion from ‘void*’ to
‘void**’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1223:
error: invalid conversion from ‘const void*’ to ‘const
__CFDictionary*’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1363:
error: invalid conversion from ‘const void*’ to ‘const
__CFString*’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1376:
error: invalid conversion from ‘const void*’ to ‘const
__CFString*’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1389:
error: invalid conversion from ‘const void*’ to ‘const
__CFString*’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1411:
error: invalid conversion from ‘const void*’ to ‘const
__CFNumber*’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1438:
error: invalid conversion from ‘const void*’ to ‘const
__CFNumber*’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1454:
error: invalid conversion from ‘const void*’ to ‘const
__CFString*’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:
In function ‘void -[HIDRemote _simulateHoldEvent:](HIDRemote*,
objc_selector*,
NSTimer*)’:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1696:
error: invalid conversion from ‘int’ to
‘HIDRemoteButtonCode’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:
In function ‘void -[HIDRemote
_handleButtonCode:isPressed:hidAttribsDict:](HIDRemote*, objc_selector*,
HIDRemoteButtonCode, BOOL,
NSMutableDictionary*)’:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1750:
error: invalid conversion from ‘int’ to
‘HIDRemoteButtonCode’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:
In function ‘void -[HIDRemote
_sendButtonCode:isPressed:hidAttribsDict:](HIDRemote*, objc_selector*,
HIDRemoteButtonCode, BOOL,
NSMutableDictionary*)’:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1810:
error: invalid conversion from ‘int’ to
‘HIDRemoteButtonCode’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:
In function ‘void -[HIDRemote _hidEventFor:from:withResult:](HIDRemote*,
objc_selector*, io_service_t, IOHIDQueueInterface**,
IOReturn)’:
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1822:
error: invalid conversion from ‘void*’ to
‘IOHIDQueueInterface**’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1834:
error: invalid conversion from ‘unsigned int’ to
‘HIDRemoteButtonCode’
/Users/Zach-Mac/github/nightingale-hacking/extensions/apple-remote/components/macremote/src/HIDRemote.mm:1860:
error: invalid conversion from ‘unsigned int’ to ‘HIDRemoteButtonCode’